### ISSUE TITLE
Unfortunately disturbs layout so much it's unusable

### ISSUE THREAD

**Issue by Friksel** [mattgrayisok/craft-dark-mode#18]
The colors of the dark mode look great, so I was looking forward to start using it, but unfortunately it's unsusable here. Not sure if in the last months Craft made changes to classes and this plugin is not maintained or it's something else, but with darkmode on 

- headers are still light and unreadable because the text is light too
- there is a huge gap, causing the most important part to move outside the screen on the right, making buttons and other elements unreachable (no scrollbar either)
- install buttons on the plugin settings page that we can't see because these move outside the screen, seem to be missing or camouflaged when expanding the screen to span over two screens
- other layout disturbancies, like missing margin between logo and brand name etc.

![dark-mode-off](https://user-images.githubusercontent.com/3089978/83011994-167be180-a01b-11ea-9442-6e515184c0bf.jpg)
![dark-mode-on](https://user-images.githubusercontent.com/3089978/83011997-17147800-a01b-11ea-996d-62dba1a7ee63.jpg)
![dark-mode-on-2](https://user-images.githubusercontent.com/3089978/83011998-17ad0e80-a01b-11ea-8b46-757294d2a4aa.jpg)

Sorry, I like the idea of the plugin and colors look great, but unfortunately it's impossible to use it here. Even with as good as all plugins turned off as you can see in the image. Hope this can get fixed as it would be nice for the eyes to use this.

**Comment by mattgrayisok** [comment]
Hey, Craft 3.4 made a lot of changes to the document structure and associated styling which caused the plugin to stop functioning correctly.

Craft will soon be incorporating its own native dark mode so it's unlikely any further work will go into this plugin to keep it updated. I'll add an appropriate note to the README

**Comment by Friksel** [comment]
Fair enough, thanks for the feedback
