### ISSUE TITLE
Plugin store LH nav border bottom white

### ISSUE THREAD

**Issue by mattgrayisok** [mattgrayisok/craft-dark-mode#2]
![image](https://user-images.githubusercontent.com/571107/50214283-c9043b00-0377-11e9-8fa1-6dc0c10b957b.png)

**Comment by richhayler** [comment]
`ul.categories li:last-child:after {border-top: 1px solid #1a1a1a !important;} `

**Comment by mattgrayisok** [comment]
Thanks, added in v1.0.1
