### ISSUE TITLE
Settings link for entries LH nav needs to be a bit more obvious

### ISSUE THREAD

**Issue by mattgrayisok** [mattgrayisok/craft-dark-mode#3]
![image](https://user-images.githubusercontent.com/571107/50214343-f5b85280-0377-11e9-9530-1b6c3afca2cc.png)

**Comment by richhayler** [comment]
`.sidebar .customize-sources {color: #e6e6e6;}`

**Comment by mattgrayisok** [comment]
Fixed in v1.0.1
