### ISSUE TITLE
FR: Toggle theme based on Safari Media Query

### ISSUE THREAD

**Issue by richhayler** [mattgrayisok/craft-dark-mode#4]
Provide a toggle to make the theme active in Safari when dark mode is enabled on macOS. 

Implement the following media query on the CSS:

`@media (prefers-color-scheme: dark) {
    dark mode css here
}`

**Comment by mattgrayisok** [comment]
In a future update I'm going to add the ability to toggle on/off with a switch in the UI. I think things might get a bit complex if I try to handle both that and the os level preference at the same time.

Closing for now but might revisit depending on feedback from the on/off toggle.
