### ISSUE TITLE
Tabs

### ISSUE THREAD

**Issue by richhayler** [mattgrayisok/craft-dark-mode#6]
```
body.ltr #main-container #main #main-content #content-container #tabs ul li a.sel:after {background: none;}
body.ltr #main-container #main #main-content #content-container #tabs ul li a:after {
background: #202020;}
```

<img width="198" alt="screen shot 2018-12-20 at 4 00 10 am" src="https://user-images.githubusercontent.com/2505643/50235382-dff46d00-040b-11e9-9f6d-fa45659b67fb.png">
<img width="201" alt="screen shot 2018-12-20 at 4 00 42 am" src="https://user-images.githubusercontent.com/2505643/50235384-e08d0380-040b-11e9-872f-f725c19c2821.png">

**Comment by mattgrayisok** [comment]
Couldn't reproduce but I just removed the gradients on these so should be finxed in V1.0.1.

Feel free to reopen if you see them after updating.
